package bdstockexchange

// sortBy is the type for constants that can be used to pass as a parameter type of sort wanted by the user
type sortBy uint8

// sortOrder ...
type sortOrder uint8

const (
	// ASC ...
	ASC sortOrder = iota
	// DESC ...
	DESC
)

const (
	// SortByTradingCode ...
	SortByTradingCode sortBy = iota
	// SortByLTP ...
	SortByLTP
	// SortByOpeningPrice ...
	SortByOpeningPrice
	// SortByHighPrice ...
	SortByHighPrice
	// SortByLowPrice ...
	SortByLowPrice
	// SortByYCP ...
	SortByYCP
	// SortByNumberOfTrades ...
	SortByNumberOfTrades
	// SortByValue ...
	SortByValue
	// SortByVolumeOfShare ...
	SortByVolumeOfShare
	// SortByPercentageChange ...
	SortByPercentageChange
	// SortByPriceChange ...
	SortByPriceChange
)
